const ACCESS_LAYER_ID = '9077D16CFE374967A8C57C78095F34EA';
const ACCESS_USER_ROLE = 'scanex';

const LOCAL_STORAGE_KEY = 'view_state';

const RESULT_MAX_COUNT = 1000;
const RESULT_MAX_COUNT_PLUS_ONE = 1001;

const MAX_CART_SIZE = 200;

const MAX_UPLOAD_OBJECTS = 200;
const MAX_UPLOAD_POINTS = 100000;

const VERSION = '2.2.5';
const VERSION_DATE = new Date(2018, 6, 27);

const LAYER_ID = '9B4733A8CBE942CE9F5E70DCAA6C1FBE'; // 'AFB4D363768E4C5FAC71C9B0C6F7B2F4'

const DEFAULT_LANGUAGE = 'rus';

const NON_EDIT_LINE_STYLE = {
    fill: false,
    weight: 2,
    opacity: 1
};

const TAB_SEARCH_NAME = 'search';
const TAB_RESULTS_NAME = 'results';

const VERSION_PATH = 'dist/version-';

const NOTIFICATION_HIDE_TIMEOUT = 2000;

export {
    ACCESS_LAYER_ID,
    ACCESS_USER_ROLE,
    LOCAL_STORAGE_KEY,
    RESULT_MAX_COUNT,
    RESULT_MAX_COUNT_PLUS_ONE,
    MAX_CART_SIZE,
    MAX_UPLOAD_POINTS,
    MAX_UPLOAD_OBJECTS,
    VERSION, VERSION_DATE,
    LAYER_ID,
    DEFAULT_LANGUAGE,
    NON_EDIT_LINE_STYLE,
    VERSION_PATH,
    TAB_SEARCH_NAME,
    TAB_RESULTS_NAME,
    NOTIFICATION_HIDE_TIMEOUT
};